#
# Copyright (C) 2021 Grakn Labs
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

agents:
  # For each agent select a `mode`, `RUN` to run without tracing, `TRACE` to run with tracing, and `OFF` to not run at all
  - name: "marriage"
    mode: OFF # no because of not
  - name: "personBirth"
    mode: TRACE # yes
  - name: "ageUpdate"
    mode: OFF # until we have macro functions
  - name: "parentship"
    mode: OFF # no because of not
  - name: "relocation"
    mode: OFF # no
  - name: "company"
    mode: TRACE  # yes
  - name: "employment"
    mode: OFF  # no
  - name: "product"
    mode: TRACE # yes
  - name: "purchase"
    mode: TRACE # yes
  - name: "friendship"
    mode: OFF # no
  - name: "meanWage"
    mode: OFF # no because we lack aggregate queries
  - name: "findLivedIn"
    mode: OFF # no
  - name: "findCurrentResidents"
    mode: OFF # no
  #  - name: "findTransactionCurrency" # no, already disabled as it times out
  #    mode: TRACE
  - name: "arbitraryOneHop"
    mode: TRACE # yes
  - name: "twoHop"
    mode: OFF # no, because of parentship
  - name: "threeHop"
    mode: OFF # no because of employment
  - name: "fourHop"
    mode: OFF # no because of employment
  - name: "findSpecificMarriage"
    mode: OFF # no because of not
  - name: "findSpecificPerson"
    mode: TRACE # yes

traceSampling:
  # Options: `"every"` for every K traces; `"log"` for logarithm with base N
  function: "every"
  arg: 10

randomSeed: 1
iterations: 100
scaleFactor: 3
databaseName: "world"
